# Generated by Django 3.2.8 on 2021-10-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211027_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['id'], 'verbose_name_plural': 'Commodity'},
        ),
        migrations.AlterField(
            model_name='commodity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
