# Generated by Django 3.2.8 on 2021-10-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_s',
            options={'ordering': ['id'], 'verbose_name_plural': 'Employee_s'},
        ),
    ]
