# Generated by Django 3.2.8 on 2021-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_s_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_s',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Employee_s'},
        ),
    ]
